/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import java.time.LocalDate;

/**
 *
 * @author thomasgiraldoduque
 */
public class frmPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form frmPrincipal
     */
    public frmPrincipal() {
        initComponents();
        setLocationRelativeTo(null);
        LlenarCombox();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlPrincipalTituloAdminCuentas = new javax.swing.JTabbedPane();
        pnlAdminCuentas = new javax.swing.JPanel();
        lblAdminCuentas = new javax.swing.JLabel();
        lblAdminClientes = new javax.swing.JPanel();
        lblPrincipalTituloAdminClientes = new javax.swing.JLabel();
        lblDocumentoCliente = new javax.swing.JLabel();
        txtDocumentoCliente = new javax.swing.JTextField();
        lblNombreCliente = new javax.swing.JLabel();
        txtNombreCliente = new javax.swing.JTextField();
        lblCorreoCliente = new javax.swing.JLabel();
        txtCorreoCliente = new javax.swing.JTextField();
        lblTelefonoCliente = new javax.swing.JLabel();
        txtTelefonoCliente = new javax.swing.JTextField();
        lblFechaNacCliente = new javax.swing.JLabel();
        lblDiaNacimientoCliente = new javax.swing.JLabel();
        lblAñoNacimientoCliente = new javax.swing.JLabel();
        lblMesNacimientoCliente = new javax.swing.JLabel();
        cbxDiaNacimientoCliente = new javax.swing.JComboBox<>();
        cbxMesNacimientoCliente = new javax.swing.JComboBox<>();
        cbxAñoNacimientoCliente = new javax.swing.JComboBox<>();
        lblEstaturaCliente = new javax.swing.JLabel();
        txtEstaturaCliente = new javax.swing.JTextField();
        lblTipoCliente = new javax.swing.JLabel();
        jComboBox4 = new javax.swing.JComboBox<>();
        btnBuscarCliente = new javax.swing.JButton();
        btnCrearCliente = new javax.swing.JButton();
        btnEliminarCliente = new javax.swing.JButton();
        btnActualizarCliente = new javax.swing.JButton();
        lblTituloPrincipal = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlPrincipalTituloAdminCuentas.setName("Admin Clientes"); // NOI18N
        pnlPrincipalTituloAdminCuentas.setOpaque(true);

        lblAdminCuentas.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        lblAdminCuentas.setText("Administrador 2");

        javax.swing.GroupLayout pnlAdminCuentasLayout = new javax.swing.GroupLayout(pnlAdminCuentas);
        pnlAdminCuentas.setLayout(pnlAdminCuentasLayout);
        pnlAdminCuentasLayout.setHorizontalGroup(
            pnlAdminCuentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAdminCuentasLayout.createSequentialGroup()
                .addGap(277, 277, 277)
                .addComponent(lblAdminCuentas)
                .addContainerGap(349, Short.MAX_VALUE))
        );
        pnlAdminCuentasLayout.setVerticalGroup(
            pnlAdminCuentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAdminCuentasLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(lblAdminCuentas)
                .addContainerGap(273, Short.MAX_VALUE))
        );

        pnlPrincipalTituloAdminCuentas.addTab("Admin Cuentas", pnlAdminCuentas);

        lblPrincipalTituloAdminClientes.setFont(new java.awt.Font("Academy Engraved LET", 2, 24)); // NOI18N
        lblPrincipalTituloAdminClientes.setText("Administrador Cliente");

        lblDocumentoCliente.setText("Documento");

        txtDocumentoCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDocumentoClienteActionPerformed(evt);
            }
        });

        lblNombreCliente.setText("Nombre");

        lblCorreoCliente.setText("Correo");

        lblTelefonoCliente.setText("Telefono");

        txtTelefonoCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelefonoClienteActionPerformed(evt);
            }
        });

        lblFechaNacCliente.setText("Fecha de Nacimiento");

        lblDiaNacimientoCliente.setText("Dia");

        lblAñoNacimientoCliente.setText("Año");

        lblMesNacimientoCliente.setText("Mes");

        lblEstaturaCliente.setText("Estatura");

        txtEstaturaCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEstaturaClienteActionPerformed(evt);
            }
        });

        lblTipoCliente.setText("Tipo de Cliente");

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Persona Natural", "Persona Juridica" }));
        jComboBox4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox4ActionPerformed(evt);
            }
        });

        btnBuscarCliente.setText("Buscar");
        btnBuscarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarClienteActionPerformed(evt);
            }
        });

        btnCrearCliente.setText("Crear");
        btnCrearCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearClienteActionPerformed(evt);
            }
        });

        btnEliminarCliente.setText("Eliminar");

        btnActualizarCliente.setText("Actualizar");

        javax.swing.GroupLayout lblAdminClientesLayout = new javax.swing.GroupLayout(lblAdminClientes);
        lblAdminClientes.setLayout(lblAdminClientesLayout);
        lblAdminClientesLayout.setHorizontalGroup(
            lblAdminClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lblAdminClientesLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(lblAdminClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, lblAdminClientesLayout.createSequentialGroup()
                        .addComponent(lblDocumentoCliente)
                        .addGap(53, 53, 53)
                        .addComponent(txtDocumentoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, lblAdminClientesLayout.createSequentialGroup()
                        .addGroup(lblAdminClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNombreCliente)
                            .addComponent(lblCorreoCliente)
                            .addComponent(lblEstaturaCliente)
                            .addComponent(lblTelefonoCliente))
                        .addGap(70, 70, 70)
                        .addGroup(lblAdminClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNombreCliente)
                            .addGroup(lblAdminClientesLayout.createSequentialGroup()
                                .addGroup(lblAdminClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtTelefonoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtCorreoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtEstaturaCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGroup(lblAdminClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, lblAdminClientesLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                        .addGroup(lblAdminClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, lblAdminClientesLayout.createSequentialGroup()
                                .addGroup(lblAdminClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jComboBox4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, lblAdminClientesLayout.createSequentialGroup()
                                        .addGroup(lblAdminClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(lblTipoCliente)
                                            .addGroup(lblAdminClientesLayout.createSequentialGroup()
                                                .addComponent(cbxDiaNacimientoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(cbxMesNacimientoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(18, 18, 18)
                                        .addComponent(cbxAñoNacimientoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(36, 36, 36))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, lblAdminClientesLayout.createSequentialGroup()
                                .addComponent(lblFechaNacCliente)
                                .addGap(106, 106, 106))))
                    .addGroup(lblAdminClientesLayout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addComponent(lblDiaNacimientoCliente)
                        .addGap(68, 68, 68)
                        .addComponent(lblMesNacimientoCliente)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblAñoNacimientoCliente)
                        .addGap(59, 59, 59)))
                .addGroup(lblAdminClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnActualizarCliente)
                    .addComponent(btnEliminarCliente)
                    .addComponent(btnBuscarCliente)
                    .addComponent(btnCrearCliente))
                .addGap(24, 24, 24))
            .addGroup(lblAdminClientesLayout.createSequentialGroup()
                .addGap(236, 236, 236)
                .addComponent(lblPrincipalTituloAdminClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        lblAdminClientesLayout.setVerticalGroup(
            lblAdminClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lblAdminClientesLayout.createSequentialGroup()
                .addGroup(lblAdminClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(lblAdminClientesLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(lblPrincipalTituloAdminClientes)
                        .addGap(36, 36, 36)
                        .addGroup(lblAdminClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblDocumentoCliente)
                            .addComponent(txtDocumentoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnBuscarCliente)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, lblAdminClientesLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblFechaNacCliente)))
                .addGroup(lblAdminClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(lblAdminClientesLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(lblAdminClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblNombreCliente)
                            .addComponent(txtNombreCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(lblAdminClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(lblAdminClientesLayout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addGroup(lblAdminClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtCorreoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblCorreoCliente)))
                            .addComponent(btnCrearCliente))
                        .addGap(18, 18, 18)
                        .addGroup(lblAdminClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTelefonoCliente)
                            .addGroup(lblAdminClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtTelefonoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnEliminarCliente))))
                    .addGroup(lblAdminClientesLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(lblAdminClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblDiaNacimientoCliente)
                            .addComponent(lblMesNacimientoCliente)
                            .addComponent(lblAñoNacimientoCliente))
                        .addGap(23, 23, 23)
                        .addGroup(lblAdminClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbxDiaNacimientoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbxMesNacimientoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbxAñoNacimientoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(lblAdminClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(lblAdminClientesLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblTipoCliente)
                        .addGap(18, 18, 18)
                        .addGroup(lblAdminClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(lblAdminClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtEstaturaCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblEstaturaCliente))
                        .addGap(34, 34, 34))
                    .addGroup(lblAdminClientesLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(btnActualizarCliente)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pnlPrincipalTituloAdminCuentas.addTab("Admin Clientes", lblAdminClientes);

        lblTituloPrincipal.setFont(new java.awt.Font("Academy Engraved LET", 1, 36)); // NOI18N
        lblTituloPrincipal.setText("Banco Ucaldas");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlPrincipalTituloAdminCuentas)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblTituloPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(188, 188, 188))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(lblTituloPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                .addComponent(pnlPrincipalTituloAdminCuentas, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtDocumentoClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDocumentoClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDocumentoClienteActionPerformed

    private void txtTelefonoClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelefonoClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelefonoClienteActionPerformed

    private void txtEstaturaClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEstaturaClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEstaturaClienteActionPerformed

    private void jComboBox4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox4ActionPerformed

    private void btnBuscarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBuscarClienteActionPerformed

    private void btnCrearClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCrearClienteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizarCliente;
    private javax.swing.JButton btnBuscarCliente;
    private javax.swing.JButton btnCrearCliente;
    private javax.swing.JButton btnEliminarCliente;
    private javax.swing.JComboBox<String> cbxAñoNacimientoCliente;
    private javax.swing.JComboBox<String> cbxDiaNacimientoCliente;
    private javax.swing.JComboBox<String> cbxMesNacimientoCliente;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JPanel lblAdminClientes;
    private javax.swing.JLabel lblAdminCuentas;
    private javax.swing.JLabel lblAñoNacimientoCliente;
    private javax.swing.JLabel lblCorreoCliente;
    private javax.swing.JLabel lblDiaNacimientoCliente;
    private javax.swing.JLabel lblDocumentoCliente;
    private javax.swing.JLabel lblEstaturaCliente;
    private javax.swing.JLabel lblFechaNacCliente;
    private javax.swing.JLabel lblMesNacimientoCliente;
    private javax.swing.JLabel lblNombreCliente;
    private javax.swing.JLabel lblPrincipalTituloAdminClientes;
    private javax.swing.JLabel lblTelefonoCliente;
    private javax.swing.JLabel lblTipoCliente;
    private javax.swing.JLabel lblTituloPrincipal;
    private javax.swing.JPanel pnlAdminCuentas;
    private javax.swing.JTabbedPane pnlPrincipalTituloAdminCuentas;
    private javax.swing.JTextField txtCorreoCliente;
    private javax.swing.JTextField txtDocumentoCliente;
    private javax.swing.JTextField txtEstaturaCliente;
    private javax.swing.JTextField txtNombreCliente;
    private javax.swing.JTextField txtTelefonoCliente;
    // End of variables declaration//GEN-END:variables

    private void LlenarCombox() {
        //Dia de naciemiento
        for (int i = 31; i >= 1; i--) {
            cbxDiaNacimientoCliente.addItem(i+"");
            
        }
       //Mes de naciemiento
        for (int i = 12; i >= 1; i--) {
            cbxMesNacimientoCliente.addItem(i + "");
            
        }
        //Añ0 de naciemiento
        for (int i =  LocalDate.now().getYear(); i >= 2000; i--) {
            cbxAñoNacimientoCliente.addItem(i + "");
            
        }
    }
}
